### ISSUE TITLE
 item click invalid in loop mode

### ISSUE THREAD

**Issue by iceuncle** [surmon-china/vue-awesome-swiper#131]
loop模式 导致图片点击失效 
 item click invalid in loop mode

**Comment by surmon-china** [comment]
#28 #21

**Comment by rkrejcii** [comment]
Hi.
I'm facing the same problem like described here and in #28 and #21. However, because I don't understand Chinese and even Google Translate didn't give me very good translation, I have to ask:

Is there any way how to make slider items clickable when the `loop` is set to `true`?

Or, if I switch the `loop` off, is there any other way how to create infinite slider, so after the last slide I will show the first one etc.?

Thanks for any hint...

**Comment by surmon-china** [comment]
@rkrejcii 
1. close loop option
2. use custom event, like: 
```html
<swiper-slide @click.native="linkToSomePage(slide.link)">
```

**Comment by rkrejcii** [comment]
@surmon-china : Thanks a lot for your quick reply.

However, it still doesn't work.

Could you please take a look on this Codepen https://codepen.io/rkrejcii/pen/yowqaX and tell me why two slides don't react on click event as all other do?

Thanks.

**Comment by surmon-china** [comment]
@rkrejcii 
Because, if the loop option is enabled, the swiper will copy two dom nodes at the beginning and end, but the event will not be copied, so any event bound is invalid. In addition, the loop option will cause a lot of unpredictable problems, which is the swiper It is recommended to avoid the use; In addition, the final solution should be:

```html
 <swiper :options="swiperOption" @click.native="slideClicked(swiper.activeIndex.slide.link)">
      <swiper-slide v-for="(slide, index) in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]">
        Slide {{ index }}
      </swiper-slide>
</swiper>
```

**Comment by quzheqing** [comment]
@surmon-china解决了。谢谢
`<swiper :options="swiperOption" @click.native="slideClicked(swiper.activeIndex.slide.link)">
      <swiper-slide v-for="(slide, index) in msg">
        Slide {{ index }}
      </swiper-slide>
</swiper>`
`methods:{
            slideClicked(index){
                let dataIndex = index%2 - 1
                console.log(this.msg[dataIndex])
            }
        }`
this.msg中的下标即为点击的对象。可以继续执行下一步操作了。

**Comment by sunceenjoy** [comment]
This is the solution:
1.  <swiper-slide onClick="_this.onSelected(this)" ...>
2. created () {
     window._this = this
}
3. methods: {
   onSelected (object) {
      var index = object.attributes['data-swiper-slide-index'].nodeValue
     console.log('you have selected slide' + index)
    },
}
