### ISSUE TITLE
Error while Integration with Nuxt.js

### ISSUE THREAD

**Issue by rohitpal99** [surmon-china/vue-awesome-swiper#54]
I am trying to integrate vue-awesome-swiper with NUXT.js.
I followed the steps as mentioned in docs for using with components

```
/ or use with component
import Vue from 'vue'
import { swiper, swiperSlide } from 'vue-awesome-swiper'

// use
export default {
  components: {
    swiper,
    swiperSlide
  }
}
```

But I am getting the error

```
ERROR in ./~/swiper/dist/css/swiper.css
Module parse failed: /....../node_modules/swiper/dist/css/swiper.css Unexpected token (15:0)
You may need an appropriate loader to handle this file type.
|  * Released on: December 13, 2016
|  */
| .swiper-container {
|   margin-left: auto;
|   margin-right: auto;
 @ ./~/babel-loader/lib?{"plugins":["transform-async-to-generator","transform-runtime"],"presets":[["es2015",{"modules":false}],"stage-2"]}!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome-swiper/swiper.vue 18:2-39
 @ ./~/vue-awesome-swiper/swiper.vue
 @ ./~/vue-awesome-swiper/index.js
 @ ./plugins/vue-touch.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```

Please suggest a way to integrate.
Thanks.

**Comment by surmon-china** [comment]
Because vue-awesome-swiper work with custom components, he can not run at nuxt.js, I need to follow the extension to directive, he can work under nuxt, thank you for your support, I will be in the near future Upgrade this version to support nuxt.js.
You can now use swiper like this, refer to the following two links:

[carrousel.vue](https://github.com/surmon-china/surmon.me/blob/master/components/article/archive/carrousel.vue)

[announcement.vue](https://github.com/surmon-china/surmon.me/blob/master/components/article/archive/announcement.vue)

**Comment by rohitpal99** [comment]
Thanks for your suggestion. I am able to integrate swiper as suggested.

**Comment by surmon-china** [comment]
[v2.3.4](https://github.com/surmon-china/vue-awesome-swiper/tree/v2.3.4) fix it.

**Comment by zaphz** [comment]
I have the same problem. You provide Vue files not solve loading problem.

**Comment by surmon-china** [comment]
@zaphz https://github.com/surmon-china/vue-awesome-swiper#use-in-ssr
