### ISSUE TITLE
Weird behavior when using virtual slides

### ISSUE THREAD

**Issue by bgondy** [surmon-china/vue-awesome-swiper#632]
#### Vue.js version and component version

```json
{
  "dependencies": {
    "swiper": "5.3.7",
    "vue": "^2.6.11",
    "vue-awesome-swiper": "4.1.0"
  },
}
```

#### Reproduction Link
https://codesandbox.io/s/vue-awesome-swiper-virtual-slides-test-p9wnf?file=/src/App.vue

#### Steps to reproduce
Slide to the end of slides

#### What is Expected?

I can't reach the last slide. everything works fine when I create a Swiper instance manually (see demo)

We should not be able to view the last slide when using vue-awesome-swiper.

This may be related to #609.

**Comment by surmon-china** [comment]
Hi! @bgondy 

Thanks for your feedback, it seems that this bug is caused by [component automatic update](https://github.com/surmon-china/vue-awesome-swiper/blob/master/src/slide.ts#L19).
You can comment the local `node_module/vue-awesome-swiper/dist/vue-awesome-swiper.js` file related 420 421 lines for testing. 

If the example works as expected after the comment, I will publish a new version soon.

**Comment by surmon-china** [comment]
[It worked!](https://codesandbox.io/s/vue-awesome-swiper-virtual-slides-test-ee1xd?file=/src/components/AwesomeComponent.vue)

1. upgrade to v4.1.1
2. add option `:auto-update="false"` to `swiper` component

**Comment by bgondy** [comment]
I'm sorry but what does `auto-update` prop do ?

**Comment by surmon-china** [comment]
> I'm sorry but what does `auto-update` prop do ?
https://github.com/surmon-china/vue-awesome-swiper/blob/master/README.md#swiper-component-api

**Comment by bgondy** [comment]
Thank you, it now works as expected.
