### ISSUE TITLE
Pagination too close

### ISSUE THREAD

**Issue by LachieKimber** [surmon-china/vue-awesome-swiper#73]
My design is messing with the pagination buttons and as a result are too close together (circles are touching). Is there a way to increase this spacing between the two?

Other than that, this plugin works like a charm!

Thanks very much.

Screenshot:
![screen shot 2017-04-07 at 10 16 43 am](https://cloud.githubusercontent.com/assets/20806055/24780557/a38925e2-1b7b-11e7-9402-420cbe90a4d3.png)

**Comment by LachieKimber** [comment]
I just tried overriding the CSS with the following code, and it didn't work:

`  .swiper-pagination-bullet
    margin-right: 10px !important`

**Comment by surmon-china** [comment]
1. You need to make sure you can control the class name of `swiper-pagination`
2. You can give the css style to the style by giving `swiper-pagination` and your own child elements
3. The example you give is most likely because you use the `scoped` tag in the host component, which causes the design style in the component to not be applied to the subcomponent
4. You can override the `swiper-pagination` css by removing the` scped` tag or adding the global css

**Comment by surmon-china** [comment]
Like this example:
https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/29-custom-pagination.vue

**Comment by surmon-china** [comment]
Incidental issues, temporarily closed, if there are similar problems please reopen.
